server:
  port: 1669

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:1668/eureka/"
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    hostname: "127.0.0.1"
spring:
  application:
    name: "spring-cloud-account"